//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaApp.Integrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetaApp.Integrations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues in authentication. Bearer token is not return..
        /// </summary>
        internal static string BearerTokenIsNotReturned {
            get {
                return ResourceManager.GetString("BearerTokenIsNotReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues in authentication. Bearer token is null..
        /// </summary>
        internal static string BearerTokenIsNull {
            get {
                return ResourceManager.GetString("BearerTokenIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dislay povided weather data..
        /// </summary>
        internal static string DislplayWeatherData {
            get {
                return ResourceManager.GetString("DislplayWeatherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File for storage will be saved to location {0}.
        /// </summary>
        internal static string FileStoragePath {
            get {
                return ResourceManager.GetString("FileStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current location path is null..
        /// </summary>
        internal static string PathIsNull {
            get {
                return ResourceManager.GetString("PathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start authentication for weather API..
        /// </summary>
        internal static string StartAuthentication {
            get {
                return ResourceManager.GetString("StartAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------\nCity: {0} \nTemperature: {1}\nDescription: {2}\n--------------------------\n.
        /// </summary>
        internal static string WeatherDataForDisplayFormat {
            get {
                return ResourceManager.GetString("WeatherDataForDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather data is null..
        /// </summary>
        internal static string WeatherDataIsNull {
            get {
                return ResourceManager.GetString("WeatherDataIsNull", resourceCulture);
            }
        }
    }
}
